---
- name: UWSGI | Install dependencies
  apt:
    name: "{{item}}"
  with_items:
    - build-essential 
  tags: [uwsgi]

- name: UWSGI | Install specific python dependencies
  apt:
    name: "{{item}}"
  with_items:
    - "{{uwsgi_python2 | ternary('python-dev', 'python3-dev')}}"
    - "{{uwsgi_python2 | ternary('python-virtualenv', 'python3-virtualenv')}}"
  tags: [uwsgi]

- name: UWSGI | Create UWSGI dir
  file:
    state: directory
    path: "{{ uwsgi_dir }}"
  tags: [uwsgi]

- name: UWSGI | Install UWSGI for Python
  pip:
    name: uwsgi
    virtualenv: "{{uwsgi_dir}}/venv"
    virtualenv_python: "{{uwsgi_python2 | ternary('python', 'python3')}}"
  tags: [uwsgi]

- name: UWSGI | Create log directory
  file:
    state: directory
    path: "{{uwsgi_log_dir}}"
    mode: 0755

- name: UWSGI | Ensure the emperor logs exists
  copy:
    content: ""
    dest: "{{uwsgi_emperor_log}}"
    force: no
    mode: 0640
  tags: [uwsgi]

- name: UWSGI | Ensure LISP dir exists
  file:
    state: directory
    path: /lisp
    mode: 0755

- name: UWSGI | Copy boot script
  template:
    src: templates/start-uwsgi.sh.j2
    dest: /lisp/start-uwsgi.sh
    mode: 0755
  tags: [uwsgi]

- name: UWSGI | Create service
  copy:
    src: files/uwsgi.service
    dest: /etc/systemd/system/
    mode: 0755
  tags: [uwsgi]

- name: UWSGI | Enable service
  service:
    name: uwsgi
    enabled: yes

- name: UWSGI | Start service
  service:
    name: uwsgi
    state: started


